#!/usr/bin/env bash

source ./common

if [[ -z "$INSTALL_PREFIX" ]] ; then INSTALL_PREFIX="/usr/local" ; fi

$INSTALL -m 644 "$BUILD_DIR/gllib/libargp.a" "$INSTALL_PREFIX/lib" &&
$INSTALL -m 644 "include/argp.h" "$INSTALL_PREFIX/include" &&

exit 0 # EX_OK
